spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
